book/urls.py
from django.urls import path,re_path

from book import views

urlpatterns = [
    # path('login/',views.login, name = 'login'),                 # FBV
    path('login/',views.LoginView.as_view(), name = 'login'),   # CBV
    # path('register/',views.register, name = 'register'),
    path('register/',views.RegisterView.as_view(), name = 'register'),
    path('exist_user/',views.exist_user),
    path('logout/',views.logout),

    path('book_list/',views.book_list, name = 'book_list'),
    # re_path(r'^book_list/(\d+)/(publisher)',views.book_list),
    re_path(r'^book_list/(?P<field_id>\d+)/(?P<field_type>publisher)',views.book_list),  # 有名分组
    # re_path(r'^book_list/(\d+)/(author)',views.book_list),
    re_path(r'^book_list/(?P<field_id>\d+)/(?P<field_type>author)',views.book_list),     # 有名分组

    path('del_book/',views.del_book, name = 'del_book'),
    re_path(r'^del_book/(\d+)/(publisher)',views.del_book),
    re_path(r'^del_book/(\d+)/(author)',views.del_book),

    path('add_book/',views.add_book,name='add_book'),
    re_path(r'^add_book/(\d+)/(publisher)',views.add_book),
    re_path(r'^add_book/(\d+)/(author)',views.add_book),

    re_path(r'^update_book/(?P<book_id>\d+)/(?P<field_id>\d+)/(?P<field_type>publisher)',views.update_book),
    re_path(r'^update_book/(?P<book_id>\d+)/(?P<field_id>\d+)/(?P<field_type>author)',views.update_book),
    re_path(r'^update_book/(?P<book_id>\d+)',views.update_book),
    # 这个得放到下面 否则会截走 上面两个 因为第一个也是正则

    path('publisher_list/',views.publisher_list, name = 'publisher_list'),
    path('del_publisher/',views.del_publisher, name = 'del_publisher'),
    path('add_publisher/',views.add_publisher, name = 'add_publisher'),
    re_path(r'^update_publisher/(\d+)',views.update_publisher),

    path('author_list/',views.author_list, name = 'author_list'),
    path('del_author/',views.del_author, name = 'del_author'),
    path('add_author/',views.add_author, name = 'add_author'),
    re_path(r'^update_author/(\d+)',views.update_author),

]

mybms/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

from book import views

urlpatterns = [
    # re_path(r'^$', views.login),
    re_path(r'^$', views.LoginView.as_view()),
    re_path(r'^',include(('book.urls','book'))),
    
]

book/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from django.utils.decorators import method_decorator
from django.core import serializers
from django.views import View
import json
import datetime
import logging
from functools import wraps

from book import models
from book import myforms
from utils.mypage import MyPaginator
from utils.hash_pwd import salt_pwd

logger = logging.getLogger(__name__)
# 生成一个名为collect的实例
collect_logger = logging.getLogger('collect')


def check_login(func):
    '''
    判断用户有没有登录得装饰器
    :param func:
    :return:
    '''
    @wraps(func)
    def inner(request,*args,**kwargs):
        # 拿到当前访问网址
        url = request.get_full_path()
        if request.session.get('user'):
            return func(request,*args,**kwargs)
        else:
            return redirect('/login/?next={}'.format(url))

    return inner


# def login(request):
#     '''
#     登录
#     :param request:
#     :return:
#     '''
#     login_form = myforms.LoginForm()
#     return render(request,'login.html',{'login_form':login_form})
#
#
# def register(request):
#     '''
#     注册
#     :param request:
#     :return:
#     '''
#     register_form = myforms.LoginForm()
#     return render(request,'register.html',{'register_form':register_form})


class LoginView(View):
    '''
    CBV 登录视图
    '''

    def get(self,request):
        login_form = myforms.LoginForm()
        return render(request, 'login.html', {'login_form': login_form})

    def post(self,request):
        login_form = myforms.LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            password = salt_pwd(password, username)
            if models.UserInfo.objects.filter(name=username,pwd=password):
                # 设置session
                request.session['user'] = username
                # request.session.set_expiry(1800) # 设置session得失效时间

                # 登录成功 写log
                logger.info('用户：'+username+' 登录成功')

                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)   # 跳转到之前访问得页面
                else:
                    return redirect(reverse('book:book_list'))

            else:
                # 登录失败，写log
                logger.error('用户：'+username+' 登录时，用户名或密码错误')

                return render(request, 'login.html', {'login_form': login_form,'error_msg':'用户名或密码错误'})
        else:
            return render(request, 'login.html', {'login_form': login_form})


class RegisterView(View):
    '''
    CBV 注册视图
    '''
    # @method_decorator(check_login)  给cbv 加装饰器 逻辑上不应该加在这里，但可以验证装饰器加成功了
    def dispatch(self, request, *args, **kwargs):
        return super(RegisterView, self).dispatch(request,*args,**kwargs)

    def get(self,request):
        register_form = myforms.LoginForm()
        return render(request,'register.html',{'register_form':register_form})

    def post(self,request):
        register_form = myforms.LoginForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password = register_form.cleaned_data.get('password')
            r_password = request.POST.get('r_password')
            if r_password == password:
                # 后台也需要判断用户名是否已存在，
                if not models.UserInfo.objects.filter(name=username).first():
                    password = salt_pwd(password,username)
                    models.UserInfo.objects.create(name=username,pwd=password)

                    # 注册成功之后，设置session登录状态
                    request.session['user'] = username

                    # 注册成功 写入log  并收集特定信息的日志
                    collect_logger.info('用户：'+username+' 注册')

                    return redirect(reverse('book:book_list'))
            else:
                return render(request,'register.html',{'register_form':register_form,'error_msg':'确认密码不符合'})

        return render(request,'register.html',{'register_form':register_form})


def exist_user(request):
    '''
    查看用户是否已经存在
    :param request:
    :return:
    '''
    if request.method == 'POST':
        username = request.POST.get('username')
        user_obj = models.UserInfo.objects.filter(name=username).first()

        reg = {'status':1,'msg':'用户已存在'} if user_obj else {'status':0,'msg':'用户不存在'}

        return HttpResponse(json.dumps(reg))


def logout(request):
    '''
    注销
    :param request:
    :return:
    '''
    request.session.delete()
    return redirect(reverse('book:login'))


# @check_login
def book_list(request,field_id = 0, field_type = 'src'):
    '''
    书列表 3中情况 从book_list下来的书  从publisher_list 下来的书 从author_list下来的书
    :param request:
    :param field_id:
    :param field_type:  /publisher_list / author_list
    :return:
    '''
    books = None

    filter_field = {
        'publisher': 'publisher_id',
        'author': 'authors__id'
    }
    field_dict = {filter_field.get(field_type): field_id} if field_type in ('publisher', 'author') else {}
    books = models.Book.objects.filter(**field_dict).values('id', 'title', 'price', 'publish_date', 'publisher__name').order_by('-id')

    ''' 注意上面得简化方法
    if field_type == 'publisher':
        books = models.Book.objects.filter(publisher_id=field_id).values('id','title','price','publish_date','publisher__name').order_by('-id')
    elif field_type == 'author':
        books = models.Book.objects.filter(authors__id=field_id).values('id','title','price','publish_date','publisher__name').order_by('-id')
    else:
         books = models.Book.objects.all().values('id', 'title', 'price', 'publish_date', 'publisher__name').order_by('-id')
    '''

    current_page_num = request.GET.get('page', 1)
    page_obj = MyPaginator(books,current_page_num)

    current_path ={'path':request.path}
    ret_dic = page_obj.show_page  # 页码返回的是字典
    ret_dic.update(current_path)  # 两个字典拼接

    # return render(request,'book_list.html',page_obj.show_page)
    return render(request,'book_list.html',ret_dic)


def del_book(request, field_id = 0, field_type = 'src'):
    '''
    删除一本书 3中情况 从book_list下来的书  从publisher_list 下来的书 从author_list下来的书
    :param request:
    :param field_id:
    :param field_type:
    :return:
    '''
    delete_id = request.POST.get('delete_id')
    if field_type == 'author':   # 清除绑定关系
        author_id = field_id
        author_obj = models.Author.objects.filter(id = author_id).first()
        try:
            author_obj.books.remove(delete_id)
            reg = {'status': 1, 'msg': '删除成功'}
        except Exception as e:
            reg = {'status':0,'msg':'删除失败'}

    else:  # 其他情况都删除书 book_list  publishe_list下来的书
        try:
            models.Book.objects.filter(id=delete_id).delete()
            reg = {'status':1,'msg':'删除成功'}
        except Exception as e:
            reg = {'status':0,'msg':'删除失败'}

    return HttpResponse(json.dumps(reg))


def add_book(request,field_id = 0, field_type = 'src'):
    '''
    增加书
    :param request:
    :param field_id:
    :param field_type:
    :return:
    '''
    current_publisher_id = 0
    current_author_id = 0
    if field_type == 'publisher':
        current_publisher_id = int(field_id)
    elif field_type == 'author':
        current_author_id = int(field_id)

    book_form = myforms.BookForm()

    if request.method == 'POST':
        if current_publisher_id:
            # 前端设置select disbaled  不能传到后台了,因此需要需要这样做
            publisher_id = current_publisher_id
        else:
            publisher_id = int(request.POST.get('publisher'))

        if request.POST.get('publish_date') != '':
            publish_date = request.POST.get('publish_date')
        else:
            publish_date = datetime.datetime.now()

        book_form = myforms.BookForm(request.POST)

        if book_form.is_valid():
            book_obj = models.Book.objects.create(
                title = book_form.cleaned_data.get('title'),
                price = book_form.cleaned_data.get('price'),
                publish_date = publish_date,
                publisher_id = publisher_id,
            )
            if current_author_id:
                book_obj.authors.add(current_author_id)  # 绑定多对多关系

            # return redirect(reverse('book:book_list')) #  因为有3种情况，分别跳到自己对应的页面下
            return redirect(request.path.replace('add_book','book_list'))

    publisher = models.Publisher.objects.all().values('id', 'name').order_by('-id')
    return render(request,'add_book.html',{'book_form':book_form,
                                            'publisher':publisher,
                                            "current_publisher_id":current_publisher_id})


def update_book(request, book_id, field_id = 0, field_type = 'src'):
    '''
    修改书
    :param request:
    :param book_id:
    :param field_id:
    :param field_type:
    :return:
    '''
    book = models.Book.objects.filter(id=book_id).first()
    book_form = myforms.BookForm()
    book_form.initial = {'title':book.title,'price':book.price}

    if request.method == 'POST':
        if request.POST.get('publish_date') != '':
            publish_date = request.POST.get('publish_date')
        else:
            publish_date = datetime.datetime.now()

        book_form = myforms.BookForm(request.POST)

        if book_form.is_valid():
            models.Book.objects.filter(id=book_id).update(
                title=book_form.cleaned_data.get('title'),
                price=book_form.cleaned_data.get('price'),
                publish_date=publish_date,
                publisher_id=request.POST.get('publisher'),
            )

            # 有3种情况，分别跳到自己对应的页面下

            if field_type in ('publisher','author'):
                new_url = reverse('book:book_list') + field_id + '/' + field_type
            else:
                new_url = reverse('book:book_list')

            return redirect(new_url)

templates/add_author.html
{% extends 'base.html' %}

{% block title %}
    <title>add_author</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>add_author</h3>
{% endblock info%}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in author_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>

        {% endfor %}
        <input class="pull-right btn btn-success" type="submit">

    </form>
{% endblock con%}

templates/add_book.html
{% extends 'base.html' %}

{% block title %}
    <title>add_book</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>add_book</h3>
{% endblock info%}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in book_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>

        {% endfor %}
        <p>
            {% load my_tag_filter %}
            <input type="hidden" id="hid_publisher_id" value="{{ current_publisher_id }}">
            <label for="id_publisher">出版社</label>
            <select name="publisher" id="id_publisher" class="form-control">
                {% for option in publisher %}
                    {# 后台传过来的 current_publisher_id 不是整数 #}
                    {% if option.id == current_publisher_id|id_filter %}
                         <option selected value="{{ option.id }}">{{ option.name }}</option>
                    {% else %}
                        <option  value="{{ option.id }}">{{ option.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </p>
        <p>
            <label for="publish_date">出版日期</label>
            <input class="form-control" type="date" name="publish_date" id="publish_date">
        </p>

        <input class="pull-right btn btn-success" type="submit">

    </form>
{% endblock con%}

{% block script %}
    {{ block.super }}
    <script type="text/javascript">
        $(function () {
            // 默认显示当前时间
            var date = new Date();
            var dataString = date.getFullYear()+"-"+num(date.getMonth()+1)+'-'+num(date.getDate());
            $('#publish_date').val(dataString);

            // 有具体的某一个publisher时，下拉框不可选
           if(Number($('#hid_publisher_id').val()) > 0){
               $('select[name=publisher]').attr('disabled','disabled');
           }

        });

        {# 格式 必须是 yyyy-MM-dd #}
        function num(obj) {
            if(obj < 10){
                return '0'+String(obj)
            }else{
                return obj
            }
        }

    </script>
{% endblock script %}

templates/add_publisher.html
{% extends 'base.html' %}

{% block title %}
    <title>add_publisher</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>add_publisher</h3>
{% endblock info%}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in publisher_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
            <input class="pull-right btn btn-success" type="submit">
        {% endfor %}

    </form>
{% endblock con%}

templates/author_list.html
{% extends 'base.html' %}

{% block title %}
    <title>author_list</title>
{% endblock title %}

{% block info %}
    <h3>authors</h3>
{% endblock info %}

{% block con %}
    <a href="{% url 'book:add_author' %}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped" >
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>姓名</th>
                <th>年龄</th>
                <th>地址</th>
                <th>修改操作</th>
                <th>删除操作</th>
            </tr>
        </thead>
        <tbody>
            {% for author in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque}}</td>
                    <td>{{ author.detail_id }}</td>
                    <td><a href="/book_list/{{ author.id }}/author/">{{ author.name }}</a></td>
                    <td>{{ author.detail__age }}</td>
                    <td>{{ author.detail__addr }}</td>
                    <td><a href="/update_author/{{ author.id }}/" class="btn btn-success">修改</a></td>
                    <td><button class="btn btn-danger my-delete">删除</button></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock con %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>base</title>
    {% endblock title %}

    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/sweetalert/sweetalert.css">
    <style type="text/css">
        .my-container{margin-top: 20px;}
        .showSweetAlert h2{padding-top: 20px;}
        .my-error-span{ color: red;display: block;font-size: 12px;}
    </style>

</head>
<body>

<div class="container my-container">
    <div class="row">
        <div class="col-md-2">
            {% block leftlist %}
                <div class="row">
                    <ul class="nav nav-pills nav-stacked my-left-con">
                        <li role="presentation"><a href="{% url 'book:book_list' %}">图书列表</a></li>
                        <li role="presentation"><a href="{% url 'book:publisher_list' %}">出版社列表</a></li>
                        <li role="presentation"><a href="{% url 'book:author_list' %}">作者列表</a></li>
                    </ul>
                </div>
            {% endblock %}

        </div>

        <div class="col-md-2">
            {% block info%}
                <h3>信息</h3>
            {% endblock info%}
            {% block cancel %}
                {% load my_tag_filter %}
                <p>欢迎：{{ request|user_tags }}</p>
                <a href="/logout/">注销</a>
            {% endblock %}
        </div>

        <div class="col-md-8">

            {% block con %}
                <h3>内容</h3>
            {% endblock %}

            {% block paginator %}
                <nav class="my-page" aria-label="Page navigation">
                    <ul class="pagination">
                        <li><a href="?page=1">首页</a></li>

                        {% if current_page_data.has_previous %}
                            <li>
                                <a href="?page={{ current_page_data.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for item in page_range %}
                            {% if current_page_num == item %}
                                <li class="active"><a href="?page={{ item }}">{{ item }}</a></li>
                            {% else %}
                                <li><a href="?page={{ item }}">{{ item }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if current_page_data.has_next %}
                            <li>
                                <a href="?page={{ current_page_data.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        <li><a href="?page={{ paginator.num_pages }}">尾页</a></li>

                    </ul>
                </nav>
            {% endblock paginator%}

        </div>
    </div>
</div>


<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script src="/static/plugins/sweetalert/sweetalert.min.js"></script>
<script src="/static/init_ajax.js"></script>

{% block script %}
    <script type="text/javascript">
        $(function () {
            //没有数据时，不显示页码
            var length = $('.table').children('tbody').children().length;
            if(length === 0){
                $('.my-page').css('display','none')
            }

            //页面加载时 左侧导航样式修改
            var pathname = window.location.pathname;
            if(pathname.indexOf("book_list/")>0){
                $('.my-left-con li').eq(0).addClass('active')
            }else if(pathname.indexOf("publisher_list/")>0){
                $('.my-left-con li').eq(1).addClass('active')
            }else if(pathname.indexOf("author_list/")>0){
                $('.my-left-con li').eq(2).addClass('active')
            }

        });

        // 删除按钮点击 获取url  会有这样的url(/book_list/2/publisher/)所以使用indexOf
        $('.my-delete').click(function () {
            var delete_id = $(this).parent().siblings('td').eq(1).text();
            var row = $(this).parent().parent();
            var pathname = window.location.pathname;
            var url = null;

            // replace 的原因 会有这样的url(/book_list/2/author/)
            // 一对多和多对多删除情况不一样，一个清除绑定关系，一个时删除
            if(pathname.indexOf("book_list/")>0){
                url = pathname.replace('/book_list/','/del_book/');
            }else if(pathname.indexOf("publisher_list/")>0){
                url = '/del_publisher/';
            }else if(pathname.indexOf("author_list/")>0){
                url = '/del_author/'
            }

            // 删除插件的应用
            swal({
                    title: "确定要删除吗？ ",
                    text: "删了就找不回来了",
                    type: "warning",
                    showCancelButton: true,  // 显不显示取消按钮
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "是，就是删除",  //按钮上的文字
                    closeOnConfirm: false
                },
                function(){
                    $.ajax({
                        url:url,
                        type:'post',
                        data:{'delete_id':delete_id},
                        success:function (ret) {
                            var data = JSON.parse(ret);
                            if(data.status === 1){
                                row.remove();
                                swal(data.msg, "恭喜您", "success");
                            }else{
                                swal(data.msg, "你可以尝试在删一次", "error");
                            }
                        }
                    });
                });
        });

    </script>

{% endblock script %}

</body>
</html>

templates/book_list.html
{% extends 'base.html' %}

{% block title %}
    <title>book_list</title>
{% endblock title %}

{% block info %}
    <h3>books</h3>
{% endblock info %}

{% block con %}
    {# 这里使用了自定义的过滤器 #}
    {% load my_tag_filter %}
    <a href="{{ path|path_filter }}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped" >
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>名称</th>
                <th>价格</th>
                <th>出版社</th>
                <th>出版日期</th>
                <th>修改操作</th>
                <th>删除操作</th>
            </tr>
        </thead>
        <tbody>
            {% for book in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque }}</td>
                    <td>{{ book.id }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.publisher__name }}</td>
                    <td>{{ book.publish_date|date:'Y-m-d' }}</td>
                    {# <td><a href="/update_book/{{ book.id }}/" class="btn btn-success">修改</a></td>#}
                    <td><a href="{{ path|update_path:book.id}}" class="btn btn-success">修改</a></td>
                    <td><button class="btn btn-danger my-delete">删除</button></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock con %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
    <title>login</title>
{% endblock %}

{% block leftlist %}
    <div class="row">
        <ul class="nav nav-pills nav-stacked my-left-con">
            <li role="presentation" class="active"><a href="{% url 'book:login' %}">登录</a></li>
            <li role="presentation"><a href="{% url 'book:register' %}">注册</a></li>
        </ul>
    </div>
{% endblock leftlist %}

{% block info %}
    <h3>欢迎来到</h3>
    <h4>图书管理系统</h4>
{% endblock %}

{% block cancel %}

{% endblock %}

{% block con %}
    <form action="" method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {% for field in login_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}
        <span class="my-error-span">{{ error_msg }}</span>
        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(function () {
            //页码不显示
            $('.my-page').css('display','none');
        })

    </script>
{% endblock %}

templates/publisher_list.html
{% extends 'base.html' %}

{% block title %}
    <title>publisher_list</title>
{% endblock title %}

{% block info %}
    <h3>publisher</h3>
{% endblock info %}

{% block con %}
    <a href="{% url 'book:add_publisher' %}" class="btn btn-info">创建</a>
    <table class="table table-bordered table-hover table-responsive table-striped" >
        <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>名称</th>
                <th>修改操作</th>
                <th>删除操作</th>
            </tr>
        </thead>
        <tbody>
            {% for publisher in current_page_data %}
                <tr>
                    <td>{{ forloop.counter|add:seque }}</td>
                    <td>{{ publisher.id }}</td>
                    <td><a href="/book_list/{{ publisher.id }}/publisher/">{{ publisher.name }}</a></td>
                    <td><a href="/update_publisher/{{ publisher.id }}/" class="btn btn-success">修改</a></td>
                    <td><button class="btn btn-danger my-delete">删除</button></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock con %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
    <title>register</title>
{% endblock %}

{% block leftlist %}
    <div class="row">
        <ul class="nav nav-pills nav-stacked my-left-con">
            <li role="presentation"><a href="{% url 'book:login' %}">登录</a></li>
            <li role="presentation" class="active"><a href="{% url 'book:register' %}">注册</a></li>
        </ul>
    </div>
{% endblock leftlist %}

{% block info %}
    <h3>欢迎来到</h3>
    <h4>图书管理系统</h4>
{% endblock %}

{% block cancel %}

{% endblock %}

{% block con %}

    <form action="" method="post" autocomplete="off" novalidate>
        {% csrf_token %}
        {% for field in register_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>
        {% endfor %}

        <p id="r_pwd">
            <label for="r_password">确认密码</label>
            <input id="r_password" name="r_password" type="password" class='form-control'>
            <span class="my-error-span">{{ error_msg }}</span>
        </p>

        <input class="pull-right btn btn-success" type="submit">
    </form>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(function () {
            //页码不显示
            $('.my-page').css('display','none');
        });

        //用户失去焦点之后 查看是否已经有该用户了
        $('#id_username').blur(function () {
            $.ajax({
                url:'/exist_user/',
                type:'post',
                data:{'username':$('#id_username').val()},
                success:function (data) {
                    data = JSON.parse(data);
                    if(data.status === 1){
                        $('#id_username').siblings('span').text(data.msg)
                    }else {
                        $('#id_username').siblings('span').text('')
                    }
                }
            })
        })

    </script>
{% endblock %}

templates/update_book.html
{% extends 'base.html' %}

{% block title %}
    <title>update_book</title>
{% endblock title %}

{% block leftlist %}

{% endblock leftlist %}

{% block info %}
    <h3>update_book</h3>
{% endblock info%}

{% block con %}
    <form action="" method="post" novalidate autocomplete="off">
        {% csrf_token %}
        {% for field in book_form %}
            <p>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span class="my-error-span">{{ field.errors.0 }}</span>
            </p>

        {% endfor %}
        <p>
            {% load my_tag_filter %}
            <label for="id_publisher">出版社</label>
            <select name="publisher" id="id_publisher" class="form-control">
                {% for option in publisher %}
                    {# 后台传过来的 current_publisher_id 不是整数 #}
                    {% if option.id == current_publisher_id|id_filter %}
                         <option selected value="{{ option.id }}">{{ option.name }}</option>
                    {% else %}
                        <option  value="{{ option.id }}">{{ option.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </p>
        <p>
            <label for="publish_date">出版日期</label>
            <input class="form-control" type="date" name="publish_date" id="publish_date" value="{{ publish_date|date:'Y-m-d' }}">
        </p>

        <input class="pull-right btn btn-success" type="submit">

    </form>
{% endblock con%}